### ISSUE TITLE
[PROPOSAL] November 13 Meeting - Agenda items

### ISSUE THREAD

**Issue by krisfreedain** [opensearch-project/technical-steering#12]
### What are you proposing?
TSC members, please propose topics you would like to discuss during the November 13th meeting. 

So far we have: 

- Streaming ingestion, separation of ingestion/serving, grpc + protobuf support - @guptashubham 
- State of OpenSearch Github project organization: which repos struggle with maintainers and why - @reta 
- experimental features: do we have to use feature flags or can we just say the feature is experimental? @yupeng9 & @AmiStrn 
- meeting cadence - do we keep it at every 2 weeks or go to monthly? @anastead & @krisfreedain

**Comment by anastead** [comment]
Discuss funding priority for documentation specifically on getting started and better organization of our docs - Anandhi, Db

**Comment by anastead** [comment]
Discuss OpenSearch proposal for 3.0 / Lucene 10 upgrade owners as @andrross  @reta thoughts?

**Comment by reta** [comment]
> Discuss OpenSearch proposal for 3.0 / Lucene 10 upgrade owners as @andrross @reta thoughts?

Thanks @anastead , this work is in progress, see please https://github.com/opensearch-project/OpenSearch/pull/16366

**Comment by reta** [comment]
|Repository|Last Commit (`main`|
|-|-|
 |https://api.github.com/repos/opensearch-project/piped-processing-language | 2023-05-10T21:44:13+00:00 |
 |https://api.github.com/repos/opensearch-project/perftop | 2023-05-10T21:46:48+00:00 |
 |https://api.github.com/repos/opensearch-project/opensearch-dashboards-sdk-js | 2023-05-10T22:34:45+00:00 |
 |https://api.github.com/repos/opensearch-project/ux | 2023-05-10T22:37:01+00:00 |
 |https://api.github.com/repos/opensearch-project/traffic-replayer | 2023-05-10T23:07:34+00:00 |
 |https://api.github.com/repos/opensearch-project/dashboards-i18n | 2023-06-07T16:30:10+00:00 |
 |https://api.github.com/repos/opensearch-project/traffic-comparator | 2023-06-07T18:21:49+00:00 |
 |https://api.github.com/repos/opensearch-project/data-prepper-documentation-website | 2023-07-03T18:20:54+00:00 |
 |https://api.github.com/repos/opensearch-project/project-website-search | 2023-08-23T18:38:00+00:00 |
 |https://api.github.com/repos/opensearch-project/simple-schema | 2023-09-07T00:29:32+00:00 |
 |https://api.github.com/repos/opensearch-project/maps | 2023-10-03T16:57:29+00:00 |
 |https://api.github.com/repos/opensearch-project/opensearch-dashboards-test-library | 2023-10-04T18:03:16+00:00 |
 |https://api.github.com/repos/opensearch-project/opensearch-cli | 2023-11-02T20:29:51+00:00 |
 |https://api.github.com/repos/opensearch-project/demos | 2023-12-21T20:47:59+00:00 |
 |https://api.github.com/repos/opensearch-project/dashboards-desktop | 2024-01-04T17:47:39+00:00 |
 |https://api.github.com/repos/opensearch-project/oui-docs-cdk | 2024-01-11T17:37:26+00:00 |
 |https://api.github.com/repos/opensearch-project/opensearch-research | 2024-03-22T00:46:50+00:00 |
 |https://api.github.com/repos/opensearch-project/sql-odbc | 2024-05-22T15:42:02+00:00 |
 |https://api.github.com/repos/opensearch-project/opensearch-ruby | 2024-07-29T14:42:55+00:00 |
 |https://api.github.com/repos/opensearch-project/logstash-input-opensearch | 2024-07-29T20:25:03+00:00 |
 |https://api.github.com/repos/opensearch-project/search-processor | 2024-08-01T20:55:11+00:00 |
 |https://api.github.com/repos/opensearch-project/opensearch-ruby-aws-sigv4 | 2024-08-06T16:58:27+00:00 |
 |https://api.github.com/repos/opensearch-project/opensearch-py-ml | 2024-08-12T19:57:35+00:00 |
 |https://api.github.com/repos/opensearch-project/skills-eval | 2024-08-21T00:22:51+00:00 |
 |https://api.github.com/repos/opensearch-project/opensearch-oci-object-storage | 2024-08-21T22:00:03+00:00 |
 |https://api.github.com/repos/opensearch-project/opensearch-clients | 2024-09-03T18:58:40+00:00 |
 |https://api.github.com/repos/opensearch-project/performance-analyzer-commons | 2024-09-04T10:30:13+00:00 |
 |https://api.github.com/repos/opensearch-project/terraform-provider-opensearch | 2024-09-18T20:00:47+00:00 |
 |https://api.github.com/repos/opensearch-project/opensearch-plugins | 2024-09-24T16:45:59+00:00 |
 |https://api.github.com/repos/opensearch-project/sql-cli | 2024-09-25T18:35:08+00:00 |
 |https://api.github.com/repos/opensearch-project/project-meta | 2024-10-14T18:58:03+00:00 |
 |https://api.github.com/repos/opensearch-project/opensearch-sdk-java | 2024-10-15T15:31:29+00:00 |
 |https://api.github.com/repos/opensearch-project/opensearch-go | 2024-10-16T17:59:56+00:00 |
 |https://api.github.com/repos/opensearch-project/skills | 2024-10-17T07:48:33+00:00 |
 |https://api.github.com/repos/opensearch-project/opensearch-plugin-template-java | 2024-10-17T18:38:28+00:00 |
 |https://api.github.com/repos/opensearch-project/foundation-website | 2024-10-19T12:29:32+00:00 |
 |https://api.github.com/repos/opensearch-project/dashboards-maps | 2024-10-22T04:24:06+00:00 |
 |https://api.github.com/repos/opensearch-project/geospatial | 2024-10-22T04:35:36+00:00 |
 |https://api.github.com/repos/opensearch-project/ml-commons-dashboards | 2024-10-22T09:19:22+00:00 |
 |https://api.github.com/repos/opensearch-project/opensearch-cluster-cdk | 2024-10-23T20:44:23+00:00 |
 |https://api.github.com/repos/opensearch-project/anomaly-detection | 2024-10-24T02:28:11+00:00 |
 |https://api.github.com/repos/opensearch-project/cross-cluster-replication | 2024-10-24T06:08:31+00:00 |
 |https://api.github.com/repos/opensearch-project/security-dashboards-plugin | 2024-10-28T14:54:53+00:00 |
 |https://api.github.com/repos/opensearch-project/performance-analyzer-rca | 2024-10-28T17:31:29+00:00 |
 |https://api.github.com/repos/opensearch-project/dashboards-query-workbench | 2024-10-28T17:41:52+00:00 |
 |https://api.github.com/repos/opensearch-project/custom-codecs | 2024-10-28T19:47:46+00:00 |
 |https://api.github.com/repos/opensearch-project/job-scheduler | 2024-10-28T20:22:38+00:00 |
 |https://api.github.com/repos/opensearch-project/dashboards-visualizations | 2024-10-28T20:55:17+00:00 |
 |https://api.github.com/repos/opensearch-project/notifications | 2024-10-28T21:05:21+00:00 |
 |https://api.github.com/repos/opensearch-project/project-tools | 2024-10-28T21:45:09+00:00 |
 |https://api.github.com/repos/opensearch-project/community | 2024-10-29T14:49:26+00:00 |
 |https://api.github.com/repos/opensearch-project/common-utils | 2024-10-29T19:49:37+00:00 |
 |https://api.github.com/repos/opensearch-project/index-management | 2024-10-29T22:44:35+00:00 |
 |https://api.github.com/repos/opensearch-project/dashboards-search-relevance | 2024-10-29T23:33:13+00:00 |
 |https://api.github.com/repos/opensearch-project/dashboards-notifications | 2024-10-30T01:59:29+00:00 |
 |https://api.github.com/repos/opensearch-project/security-analytics | 2024-10-30T15:03:08+00:00 |
 |https://api.github.com/repos/opensearch-project/security-analytics-dashboards-plugin | 2024-10-31T02:20:38+00:00 |
 |https://api.github.com/repos/opensearch-project/alerting | 2024-10-31T21:15:12+00:00 |
 |https://api.github.com/repos/opensearch-project/ml-commons | 2024-11-01T17:09:03+00:00 |
 |https://api.github.com/repos/opensearch-project/reporting | 2024-11-01T19:57:48+00:00 |
 |https://api.github.com/repos/opensearch-project/opensearch-sdk-py | 2024-11-02T04:31:01+00:00 |
 |https://api.github.com/repos/opensearch-project/opensearch-system-templates | 2024-11-04T10:04:28+00:00 |
 |https://api.github.com/repos/opensearch-project/logstash-output-opensearch | 2024-11-04T22:13:12+00:00 |
 |https://api.github.com/repos/opensearch-project/opensearch-php | 2024-11-05T09:10:16+00:00 |
 |https://api.github.com/repos/opensearch-project/performance-analyzer | 2024-11-05T16:15:05+00:00 |
 |https://api.github.com/repos/opensearch-project/user-behavior-insights | 2024-11-05T21:40:55+00:00 |
 |https://api.github.com/repos/opensearch-project/helm-charts | 2024-11-05T23:41:44+00:00 |
 |https://api.github.com/repos/opensearch-project/ansible-playbook | 2024-11-05T23:41:48+00:00 |
 |https://api.github.com/repos/opensearch-project/opensearch-hadoop | 2024-11-06T00:25:30+00:00 |
 |https://api.github.com/repos/opensearch-project/index-management-dashboards-plugin | 2024-11-06T07:52:16+00:00 |
 |https://api.github.com/repos/opensearch-project/opensearch-js | 2024-11-06T16:55:34+00:00 |
 |https://api.github.com/repos/opensearch-project/dashboards-reporting | 2024-11-06T18:56:47+00:00 |
 |https://api.github.com/repos/opensearch-project/dashboards-anywhere | 2024-11-06T20:03:38+00:00 |
 |https://api.github.com/repos/opensearch-project/sql | 2024-11-06T22:03:54+00:00 |
 |https://api.github.com/repos/opensearch-project/opentelemetry-demo | 2024-11-06T22:04:16+00:00 |
 |https://api.github.com/repos/opensearch-project/observability | 2024-11-06T22:25:29+00:00 |
 |https://api.github.com/repos/opensearch-project/sql-jdbc | 2024-11-06T22:31:16+00:00 |
 |https://api.github.com/repos/opensearch-project/reporting-cli | 2024-11-06T22:33:06+00:00 |
 |https://api.github.com/repos/opensearch-project/asynchronous-search | 2024-11-06T22:38:28+00:00 |
 |https://api.github.com/repos/opensearch-project/oui | 2024-11-06T22:45:25+00:00 |
 |https://api.github.com/repos/opensearch-project/opensearch-benchmark | 2024-11-07T04:15:49+00:00 |
 |https://api.github.com/repos/opensearch-project/opensearch-dashboards-functional-test | 2024-11-07T09:24:46+00:00 |
 |https://api.github.com/repos/opensearch-project/opensearch-catalog | 2024-11-07T18:19:10+00:00 |
 |https://api.github.com/repos/opensearch-project/automation-app | 2024-11-07T19:57:31+00:00 |
 |https://api.github.com/repos/opensearch-project/anomaly-detection-dashboards-plugin | 2024-11-08T00:27:29+00:00 |
 |https://api.github.com/repos/opensearch-project/project-website | 2024-11-08T16:58:56+00:00 |
 |https://api.github.com/repos/opensearch-project/k-NN | 2024-11-08T17:33:32+00:00 |
 |https://api.github.com/repos/opensearch-project/opensearch-learning-to-rank-base | 2024-11-08T22:38:24+00:00 |
 |https://api.github.com/repos/opensearch-project/opensearch-net | 2024-11-11T10:29:02+00:00 |
 |https://api.github.com/repos/opensearch-project/spring-data-opensearch | 2024-11-11T12:59:52+00:00 |
 |https://api.github.com/repos/opensearch-project/technical-steering | 2024-11-11T15:35:21+00:00 |
 |https://api.github.com/repos/opensearch-project/neural-search | 2024-11-11T17:50:46+00:00 |
 |https://api.github.com/repos/opensearch-project/opensearch-rs | 2024-11-11T18:30:58+00:00 |
 |https://api.github.com/repos/opensearch-project/flow-framework | 2024-11-11T18:54:49+00:00 |
 |https://api.github.com/repos/opensearch-project/opensearch-ci | 2024-11-11T19:47:34+00:00 |
 |https://api.github.com/repos/opensearch-project/opensearch-testcontainers | 2024-11-11T20:19:32+00:00 |
 |https://api.github.com/repos/opensearch-project/opensearch-build-libraries | 2024-11-11T21:02:15+00:00 |
 |https://api.github.com/repos/opensearch-project/security | 2024-11-11T21:14:10+00:00 |
 |https://api.github.com/repos/opensearch-project/query-insights | 2024-11-11T21:16:07+00:00 |
 |https://api.github.com/repos/opensearch-project/query-insights-dashboards | 2024-11-11T21:16:43+00:00 |
 |https://api.github.com/repos/opensearch-project/opensearch-benchmark-workloads | 2024-11-11T21:49:54+00:00 |
 |https://api.github.com/repos/opensearch-project/opensearch-java | 2024-11-11T22:16:13+00:00 |
 |https://api.github.com/repos/opensearch-project/.github | 2024-11-11T23:02:54+00:00 |
 |https://api.github.com/repos/opensearch-project/alerting-dashboards-plugin | 2024-11-11T23:13:06+00:00 |
 |https://api.github.com/repos/opensearch-project/opensearch-build | 2024-11-12T00:08:56+00:00 |
 |https://api.github.com/repos/opensearch-project/dashboards-assistant | 2024-11-12T01:30:53+00:00 |
 |https://api.github.com/repos/opensearch-project/OpenSearch-Dashboards | 2024-11-12T01:52:34+00:00 |
 |https://api.github.com/repos/opensearch-project/opensearch-devops | 2024-11-12T03:08:35+00:00 |
 |https://api.github.com/repos/opensearch-project/opensearch-api-specification | 2024-11-12T04:09:37+00:00 |
 |https://api.github.com/repos/opensearch-project/opensearch-migrations | 2024-11-12T11:13:52+00:00 |
 |https://api.github.com/repos/opensearch-project/opensearch-py | 2024-11-12T14:21:32+00:00 |
 |https://api.github.com/repos/opensearch-project/opensearch-k8s-operator | 2024-11-12T14:52:39+00:00 |
 |https://api.github.com/repos/opensearch-project/dashboards-flow-framework | 2024-11-12T16:28:31+00:00 |
 |https://api.github.com/repos/opensearch-project/opensearch-metrics | 2024-11-12T17:48:50+00:00 |
 |https://api.github.com/repos/opensearch-project/documentation-website | 2024-11-12T18:10:21+00:00 |
 |https://api.github.com/repos/opensearch-project/opensearch-spark | 2024-11-12T18:30:46+00:00 |
 |https://api.github.com/repos/opensearch-project/OpenSearch | 2024-11-12T18:52:41+00:00 |
 |https://api.github.com/repos/opensearch-project/dashboards-observability | 2024-11-12T19:03:40+00:00 |
 |https://api.github.com/repos/opensearch-project/data-prepper | 2024-11-12T19:20:25+00:00 |

**Comment by krisfreedain** [comment]
Thank you all for the agenda topics. Meeting complete. 

Will carry forward the agenda items we did not have time for in the next meeting:

https://github.com/opensearch-project/technical-steering/issues/15
