### ISSUE TITLE
[PROPOSAL] Require 2 maintainers to approve PRs in this repo

### ISSUE THREAD

**Issue by dblock** [opensearch-project/technical-steering#6]
### What are you proposing?

Most changes in this repo will be first discussed in the TSC, then we will merge any changes to this repo with 2 approvers.

### What users have asked for this feature?

TSC

### What problems are you trying to solve?

Ensure the contents of this repo are as intended.

### What is the developer experience going to be?

Any change to content of this repo via PR will require 2 approvers.

**Comment by dblock** [comment]
@krisfreedain Did the TSC vote on 2 approvers, can I implement this?

**Comment by krisfreedain** [comment]
@dblock - the TSC did vote to approve - let's move forward on this. thanks again

**Comment by dblock** [comment]
I made the changes.

<img width="764" alt="Screenshot 2024-12-09 at 9 39 27 PM" src="https://github.com/user-attachments/assets/a386559e-8d89-44bf-a966-e0e14d990031">
