### ISSUE TITLE
[PROPOSAL] Require bake time in the repo.

### ISSUE THREAD

**Issue by dblock** [opensearch-project/technical-steering#7]
### What are you proposing?

Require 48 hour bake time in this repo for PRs before they are merged.

### What users have asked for this feature?

TSC

### What problems are you trying to solve?

We want to collect feedback and input on issues, especially for important things.

### What is the developer experience going to be?

Any PR will have to sit for 48 hours without changes or comments before getting merged.

**Comment by dblock** [comment]
https://github.com/opensearch-project/.github/blob/main/.github/workflows/bake_time.yml

**Comment by dblock** [comment]
Whomever is doing this one, please also pickup https://github.com/opensearch-project/community/issues/52 which is identical but in a different repo.

**Comment by krisfreedain** [comment]
> Whomever is doing this one, please also pickup [opensearch-project/community#52](https://github.com/opensearch-project/community/issues/52) which is identical but in a different repo.

52 was closed since we moved the mentioned files into this, more appropriate repo.
